appshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls')),
    path('Contact_us/', include('Contact.urls')),
    path('post_detail/', include('post_detail.urls')),
    path('', include('accounts.urls')),
    path('order/', include('order.urls')),

]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('cat/<cat>', views.home.as_view(), name='navbar'),
]

post_detail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<slug:slug>', views.detail.as_view(), name='detail')
]

post_detail/models.py
from cloudinary.models import CloudinaryField
from django.db import models
from django.utils.text import slugify

from accounts.models import User


class Category(models.Model):
    cat = models.CharField(max_length=100, null=True)
    parent = models.ManyToManyField('Category', blank=True)
    is_active = models.BooleanField(null=True)

    def __str__(self):
        return self.cat


class Information(models.Model):
    image = CloudinaryField('image')
    name = models.CharField(max_length=100)
    star = models.IntegerField()
    pre_price = models.CharField(max_length=100, null=True)
    price = models.IntegerField(null=True)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    descriotions = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True)
    is_delete = models.BooleanField(null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            if Information.objects.filter(slug=self.slug).exists():
                self.slug = slugify(self.name + '-' + str(self.id))
            super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name


class ProductVisit(models.Model):
    product = models.ForeignKey('Information', on_delete=models.CASCADE)
    ip = models.CharField(max_length=30)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product.name} / {self.ip}'

post_detail/views.py
from django.views.generic import DetailView

from utils.http_service import get_client_ip
from .models import Information, ProductVisit


class detail(DetailView):
    template_name = 'post_detail/detail.html'
    model = Information
    context_object_name = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loaded_product = self.object
        user_ip = get_client_ip(self.request)
        user_id = None

        if self.request.user.is_authenticated:
            user_id = self.request.user.id
        has_been_visited = ProductVisit.objects.filter(ip__iexact=user_ip, product_id=loaded_product.id).exists()

        if not has_been_visited:
            new_visit = ProductVisit(ip=user_ip, user_id=user_id, product_id=loaded_product.id)
            new_visit.save()
        context['visit'] = ProductVisit.objects.all()
        context['information'] = Information.objects.all()
        for a in ProductVisit.objects.all():
            if a.product.id == a.id:
                print(a.product.name, a.ip.count)
        return context

post_detail/templates/post_detail/detail.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}
{% block sidebar %}
    <!-- Topbar Start -->
    {% render_partial 'home.views.header' %}
    <!-- Topbar End -->
    <!-- Navbar Start -->
    {% render_partial 'home.views.navbar' %}
    <!-- Navbar End -->

{% endblock %}

{% block content %}

    <!-- Shop Detail Start -->
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 pb-5">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner border">

                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="{{ slug.image.url }}" alt="Image">
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-lg-7 pb-5">
                <h3 class="font-weight-semi-bold">{{ slug.name }}</h3>
                <div class="d-flex mb-3">
                    <div class="text-primary mr-2">
                        {#                        {% for star in slug.star %}#}
                        {#                            <small class="fas fa-star"></small>#}
                        {#                        {% endfor %}#}


                    </div>
                    <small class="pt-1">( {{ slug.productvisit_set.count }} Reviews)</small>

                </div>
                <h3 class="font-weight-semi-bold mb-4">$ {{ slug.price }}</h3>
                <p class="mb-4">{{ slug.descriotions }}</p>
                <div class="d-flex mb-3">
                    <p class="text-dark font-weight-medium mb-0 mr-3">Sizes:</p>
                    <form>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-1" name="size">
                            <label class="custom-control-label" for="size-1">XS</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-2" name="size">
                            <label class="custom-control-label" for="size-2">S</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-3" name="size">
                            <label class="custom-control-label" for="size-3">M</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-4" name="size">
                            <label class="custom-control-label" for="size-4">L</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="size-5" name="size">
                            <label class="custom-control-label" for="size-5">XL</label>
                        </div>
                    </form>
                </div>
                <div class="d-flex mb-4">
                    <p class="text-dark font-weight-medium mb-0 mr-3">Colors:</p>
                    <form>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-1" name="color">
                            <label class="custom-control-label" for="color-1">Black</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-2" name="color">
                            <label class="custom-control-label" for="color-2">White</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-3" name="color">
                            <label class="custom-control-label" for="color-3">Red</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-4" name="color">
                            <label class="custom-control-label" for="color-4">Blue</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-5" name="color">
                            <label class="custom-control-label" for="color-5">Green</label>
                        </div>
                    </form>
                </div>
                <div class="d-flex align-items-center mb-4 pt-2">
                    <div class="input-group quantity mr-3" style="width: 130px;">
                        <input type="number" class="form-control bg-secondary text-center" id="product-count" min="1" value="1">
                    </div>
                    <button class="btn btn-primary px-3"  onclick="addProductToOrder({{ slug.id }}) "><i class="fa fa-shopping-cart mr-1"></i> Add To Cart</button>
                </div>
                <div class="d-flex pt-2">
                    <p class="text-dark font-weight-medium mb-0 mr-2">Share on:</p>
                    <div class="d-inline-flex">
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- Shop Detail End -->


{% endblock %}