appshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls')),
    path('Contact_us/', include('Contact.urls')),
    path('post_detail/', include('post_detail.urls')),
    path('', include('accounts.urls')),
    path('order/', include('order.urls')),

]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('cat/<cat>', views.home.as_view(), name='navbar'),
]

post_detail/models.py
from cloudinary.models import CloudinaryField
from django.db import models
from django.utils.text import slugify

from accounts.models import User


class Category(models.Model):
    cat = models.CharField(max_length=100, null=True)
    parent = models.ManyToManyField('Category', blank=True)
    is_active = models.BooleanField(null=True)

    def __str__(self):
        return self.cat


class Information(models.Model):
    image = CloudinaryField('image')
    name = models.CharField(max_length=100)
    star = models.IntegerField()
    pre_price = models.CharField(max_length=100, null=True)
    price = models.IntegerField(null=True)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    descriotions = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True)
    is_delete = models.BooleanField(null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            if Information.objects.filter(slug=self.slug).exists():
                self.slug = slugify(self.name + '-' + str(self.id))
            super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name


class ProductVisit(models.Model):
    product = models.ForeignKey('Information', on_delete=models.CASCADE)
    ip = models.CharField(max_length=30)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product.name} / {self.ip}'

templates/shared/_layout.html
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>EShop</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    {% include 'shared/header_references.html' %}
</head>
<body>

{% block sidebar %}

{% endblock %}
{% block navbar %}

{% endblock %}

<!-- Products Start -->
{% block content %}{% endblock %}
<!-- Products End -->
<!-- Footer Start -->
{% render_partial 'home.views.footer' %}

<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

{% include 'shared/footer_references.html' %}
</body>

</html>

templates/shared/footer_parsial.html
<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span
                        class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
            </a>
            <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore
                amet erat.</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>{{ site.address1 }}</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>{{ site.email1 }}</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>{{ site.phone1 }}</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="{% url 'home' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping
                            Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i
                                class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="{% url 'Contact' %}"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>

                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="Your Name"
                                   required="required"/>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                   required="required"/>
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="#">{{ site.copyright }}</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
{#            <img class="img-fluid" src="/static/img/payments.png" alt="">#}
        </div>
    </div>
</div>

templates/shared/footer_references.html
<!-- JavaScript Libraries -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="/static/lib/easing/easing.min.js"></script>
<script src="/static/lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Contact Javascript File -->
<script src="/static/mail/jqBootstrapValidation.min.js"></script>
<script src="/static/mail/contact.js"></script>


<!-- Template Javascript -->
<script src="/static/js/main.js"></script>


<script>
    var slider = document.getElementById("myRange");
    var output = document.getElementById("demo");
    output.innerHTML = slider.max;

    slider.oninput = function () {
        output.innerHTML = this.value;
    }

    function filterProducts() {
        const filterPrice = $('#myRange').val();
        const end_price = filterPrice.split(',')[0];
        $('#end_price').val(end_price);
        $('#filter_form').submit();
    }

    function addProductToOrder(product_id) {

        const productCount = $('#product-count').val() || 1;

        $.get('/order/add-to-order?product_id=' + product_id + '&count=' + productCount).then(value => {
            Swal.fire({

                text: value.text,
                icon: value.icon,
                showCancelButton: false,
                confirmButtonColor: '#3085d6',
                confirmButtonText: value.confirm_button_text
            }).then((result) => {
                if (result.isConfirmed && value.status === 'not_auth') {
                    window.location.replace('/login');
                }
            });

        });


    }

    function removeOrderDetail(detailId) {
        $.get('/order/Shoppingl?detail_id=' + detailId).then(value => {
            console.log(value)
        });
    }

    function success() {
        var element = document.getElementById("success");
        element.classList.add("alert-success");
        document.getElementById('success').innerHTML = "email has been sent ";
        alert(' chack your mail to activate your account.if you could not find it chack your spams')

    }

    function removeOrderDetail(detailId) {
    $.get('/order/remove-order-detail?detail_id=' + detailId).then(res => {
        if (res.status === 'success') {
            $('#order-detail-content').html(res.body);
        }
    });
}
function changeOrderCount(detailId, state) {
   $.get('/order/change-order-detail?detail_id=' + detailId + '&state=' + state).then(res => {
        if (res.status === 'success') {
            $('#order-detail-content').html(res.body);
        }
    });
}
</script>

templates/shared/header_parsial.html
<div class="container-fluid">
    <div class="row bg-secondary py-2 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark" href="">FAQs</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Help</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Support</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark px-2" href="">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-dark pl-2" href="">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="" class="text-decoration-none">
                <h1 class="m-0 display-5 font-weight-semi-bold"><span
                        class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
            </a>
        </div>
        <div class="col-lg-6 col-6 text-left">
            <form action="">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products">
                    <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">
            {% if request.user.is_authenticated %}


                <a href="" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <span class="badge">0</span>
                </a>
                <a href="{% url 'Shopping_Cart' %}" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">0</span>
                </a>

            {% endif %}

        </div>
    </div>
</div>

templates/shared/header_references.html
 <!-- Favicon -->
{#    <link href="/static/img/favicon.ico" rel="icon">#}

    <!-- Google Web Fonts -->
{#<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>#}
{#    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">#}

    <!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" integrity="sha512-PgQMlq+nqFLV4ylk1gwUOgm6CtIIXkKwaIHp/PAIWHzig/lKZSEGKEysh0TCVbHJXCLN7WetD8TFecIky75ZfQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />    <!-- Libraries Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">

templates/shared/navbar_parsial.html
<div class="container-fluid mb-5">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100"
               data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0"
                 id="navbar-vertical">
                <div class="navbar-nav w-100 overflow-hidden">

                    {% for category in nav_category %}
                        {% if category.information_set.all %}
                        <a href="{% url 'navbar' cat=category.cat %}" class="nav-item nav-link">{{ category.cat }}</a>
                        {% endif %}
                    {% endfor %}

                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span
                            class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto py-0">
                        {% if request.user.is_authenticated %}
                            {% if request.user.is_superuser %}

                                <a href="/admin" class="nav-item nav-link">admin</a>

                            {% endif %}

                            <a href="{% url 'home' %}" class="nav-item nav-link">Home</a>
                            <a href="{% url 'Contact' %}" class="nav-item nav-link">Contact</a>
                            <a href="{% url 'Logout' %}" class="nav-item nav-link">Logout</a>

                        {% else %}
                            <a href="{% url 'home' %}" class="nav-item nav-link">Home</a>
                            <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
                            <a href="{% url 'register' %}" class="nav-item nav-link">Register</a>
                            <a href="{% url 'Contact' %}" class="nav-item nav-link">Contact</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
            <div id="header-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% for slide in Slide %}
                        <div class="carousel-item {% if forloop.first %}active {% endif %}" style="height: 410px;">
                            <img class="img-fluid" src="{{ slide.image.url }}" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">{{ slide.description }}</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">{{ slide.title }}</h3>
                                    <a href="{{ slide.url }}" target="'_blank" class="btn btn-light py-2 px-3">Shop Now</a>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                </div>
                <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-prev-icon mb-n2"></span>
                    </div>
                </a>
                <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-next-icon mb-n2"></span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

templates/shared/other_navbar_parsial.html
<div class="container-fluid">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100"
               data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light"
                 id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
                <div class="navbar-nav w-100 overflow-hidden" >

                    {% for category in nav_category %}
                            <a href="{% url 'navbar' cat=category.cat %}" class="nav-item nav-link">{{ category.cat }}</a>
                        {% endfor %}
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span
                            class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto py-0">
                        {% if request.user.is_authenticated %}
                            {% if request.user.is_superuser %}
                                <a href="/admin" class="nav-item nav-link">admin</a>
                            {% endif %}
                            <a href="{% url 'home' %}" class="nav-item nav-link">Home</a>
                            <a href="{% url 'Contact' %}" class="nav-item nav-link">Contact</a>
                            <a href="{% url 'Logout' %}" class="nav-item nav-link">Logout</a>

                        {% else %}
                            <a href="{% url 'home' %}" class="nav-item nav-link">Home</a>
                            <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
                            <a href="{% url 'register' %}" class="nav-item nav-link">Register</a>
                            <a href="{% url 'Contact' %}" class="nav-item nav-link">Contact</a>
                        {% endif %}
                    </div>
                </div>
            </nav>

        </div>
    </div>
</div>